Creare ISPIRATORE.md
softeng2223-inf-uniba/progetto2223-floyd pull request #8
Opened 2023-04-07 11:07 UTC by Martycap

Ho creato il file markdown ISPIRATORE.md che contiene la biografia del nostro ispiratore: Floyd.
closes #5

2023-04-07 14:52 UTC, Donatooooooo approved these changes
La richiesta è stata rispettata.

2023-04-07 19:31 UTC, armandolattaruli requested changes
Al fine di rendere più leggibile la biografia - e non farla sembrare solo un _wall of text_ - propongo di aggiungere dei titoli per le relative sezioni, intervenendo quindi sullo stile del file.

2023-04-08 09:54 UTC, Donatooooooo requested changes
Potresti aggiungere i paragrafi e mettere il testo giustificato

2023-04-08 10:16 UTC, Martycap commented
Va bene, grazie per i vostri suggerimenti, procedo con le modifiche.

2023-04-08 20:48 UTC, armandolattaruli approved these changes
Le sezioni sono state titolate correttamente e l'impatto visivo è nettamente migliore rispetto a prima. Per me non ci sono altre modifiche da apportare.

2023-04-09 07:57 UTC, Donatooooooo approved these changes
Va bene

2023-04-09 09:31 UTC, merged